name: GitHub Repo Backup

on:
  schedule:
    # Run every 5 minutes (minimum GitHub supports)
    - cron: "*/5 * * * *"
  workflow_dispatch:   # optional manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Backup Directory
        run: |
          BACKUP_DIR=/home/runner/github_backup
          mkdir -p $BACKUP_DIR
          echo "Backup directory created at $BACKUP_DIR"

      - name: Create Repo Backup Archive
        run: |
          BACKUP_DIR=/home/runner/github_backup
          TIMESTAMP=$(date +%F_%H-%M-%S)
          BACKUP_FILE=$BACKUP_DIR/repo_backup_$TIMESTAMP.tar.gz

          # Create a tar.gz of repo
          tar -czf $BACKUP_FILE .

          # Keep only last 3 backups
          ls -1t $BACKUP_DIR/repo_backup_*.tar.gz | tail -n +4 | xargs rm -f || true

          echo "✅ Backup created: $BACKUP_FILE"

      - name: Upload Backup Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-repo-backup
          path: /home/runner/github_backup/*.tar.gz